#cloud-config

package_upgrade: true
packages:
  - adminer
  - mysql-server
  - openjdk-17-jre-headless
  - unzip

runcmd:
  # Set up variables.
  - export ARCHIVESSPACE_VERSION=v4.0.0-RC1
  - export ARCHIVESSPACE_HOME=/opt/archivesspace
  - export SOLR_VERSION=9.7.0
  - export SOLR_ROOT=/opt/solr
  - export SOLR_HOME="$SOLR_ROOT/server/solr"
  - export SOLR_JETTY_HOST=0.0.0.0
  - export SOLR_MODULES=analysis-extras
  - export MYSQL_CONNECTOR_JAVA_VERSION=9.1.0
  # Install ArchivesSpace.
  - echo "🚧 INSTALLING ARCHIVESSPACE"
  - curl --silent --location "https://github.com/archivesspace/archivesspace/releases/download/${ARCHIVESSPACE_VERSION}/archivesspace-${ARCHIVESSPACE_VERSION}.zip" --output "/var/tmp/archivesspace-${ARCHIVESSPACE_VERSION}.zip"
  - unzip -q "/var/tmp/archivesspace-${ARCHIVESSPACE_VERSION}.zip" -d /opt
  - rm /var/tmp/archivesspace-${ARCHIVESSPACE_VERSION}.zip
  # Install ArchivesSpace plugins.
  # - git clone https://github.com/lyrasis/aspace-reindexer.git "$ARCHIVESSPACE_HOME/plugins/reindexer"
  # - git clone https://github.com/alexduryee/timewalk.git "$ARCHIVESSPACE_HOME/plugins/timewalk"
  ## Install Solr.
  - echo "🚧 INSTALLING SOLR"
  - curl --silent --location "https://archive.apache.org/dist/solr/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz" --output "/var/tmp/solr-${SOLR_VERSION}.tgz"
  - tar xzf /var/tmp/solr-${SOLR_VERSION}.tgz solr-${SOLR_VERSION}/bin/install_solr_service.sh --strip-components=2
  - bash ./install_solr_service.sh /var/tmp/solr-${SOLR_VERSION}.tgz
  - echo "SOLR_MODULES=analysis-extras" >> /etc/default/solr.in.sh
  - echo "SOLR_JETTY_HOST=0.0.0.0" >> /etc/default/solr.in.sh
  - mkdir --parents "$SOLR_HOME/configsets/archivesspace/conf"
  - cp "$ARCHIVESSPACE_HOME/solr/schema.xml" "$SOLR_HOME/configsets/archivesspace/conf/"
  - curl --silent --location "https://gist.github.com/t4k/3d0173a1d265a2693fd165b6c0808881/raw/d8513ffc49d5d53ce7ea81dc20c9db1c41ab848a/solrconfig.xml" --output "$SOLR_HOME/configsets/archivesspace/conf/solrconfig.xml"
  - cp "$ARCHIVESSPACE_HOME/solr/stopwords.txt" "$SOLR_HOME/configsets/archivesspace/conf/"
  - cp "$ARCHIVESSPACE_HOME/solr/synonyms.txt" "$SOLR_HOME/configsets/archivesspace/conf/"
  - su --login solr --command "$SOLR_ROOT/bin/solr create -c archivesspace -d archivesspace"
  - rm /var/tmp/solr-${SOLR_VERSION}.tgz
  - service solr restart
  ## Install AWS CLI.
  - echo "🚧 INSTALLING AWS CLI"
  - curl --silent --location "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" --output "/var/tmp/awscliv2.zip"
  - unzip -q /var/tmp/awscliv2.zip
  - rm /var/tmp/awscliv2.zip
  - ./aws/install
  - rm --recursive ./aws
  # Install MySQL Connector/J.
  - echo "🚧 INSTALLING MYSQL CONNECTOR/J"
  - curl --silent --location "https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/${MYSQL_CONNECTOR_JAVA_VERSION}/mysql-connector-j-${MYSQL_CONNECTOR_JAVA_VERSION}.jar" --output "/opt/archivesspace/lib/mysql-connector-java-${MYSQL_CONNECTOR_JAVA_VERSION}.jar"
  # Enable Adminer.
  - echo "🚧 ENABLING ADMINER"
  - a2enconf adminer
  - systemctl reload apache2
